name: VitalRules
version: @version@
main: com.tamrielnetwork.vitalrules.VitalRules
api-version: 1.17
authors: [ Tamriel Network ]
website: https://tamriel.site
description: Gives players the ability to see server rules.
commands:
  vitalrules:
    description: "Main command"
    usage: "/vitalrules"
permissions:
  vitalrules.rules:
    description: "Permission to see server rules"
    default: op