name: VitalRules
version: @version@
main: com.tamrielnetwork.vitalrules.VitalRules
api-version: 1.17
authors: [ Tamriel Network ]
website: https://tamriel.site
description: Gives you the ability to fly and toggle fly speed.
commands:
  vitalrules:
    description: "Main command"
    usage: "/vitalrules"
permissions:
  vitalrules.fly:
    description: "Permission to toggle fly"
    default: op
  vitalrules.fly.others:
    description: "Permission to toggle fly for other players"
    default: op
  vitalrules.flyspeed:
    description: "Permission to set flyspeed"
    default: op
  vitalrules.flyspeed.others:
    description: "Permission to set flyspeed for other players"
    default: op
  vitalrules.fly.worldchange:
    description: "Permission to keep fly on worldchange"
    default: op
  vitalrules.fly.gamemodechange:
    description: "Permission to keep fly on gamemodechange"
    default: op
  vitalrules.fly.login:
    description: "Permission to keep fly on login"
    default: op